spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLECLIENTID}
            client-secret: ${GOOGLECLIENTSECRET}
            scope: profile, email

          naver:
            client-id: ${NAVERCLIENTID}
            client-secret: ${NAVERCLIENTSECRET}
            #            redirect-uri: http://localhost:8080/login/oauth2/code/naver #(설정한 redirect URI)
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: ${KAKAOCLIENTID}
            client-secret: ${KAKAOCLIENTSECRET}
            #            redirect-uri: http://localhost:8080/login/oauth2/code/kakao #(설정한 redirect URI)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id